# A sample Guardfile
# More info at https://github.com/guard/guard#readme

## Uncomment and set this to only include directories you want to watch
# directories %w(app lib config test spec features) \
#  .select{|d| Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")}

## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), then you will want to move
## the Guardfile to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"

repl_options =
  [ "--ghc-options=-ignore-dot-ghci" \
  ]

guard :haskell, repl_options: repl_options do
 # watch(%r{test/.+Spec\.l?hs$})
  watch(%r{src/.+\.l?hs$})
 # watch(%r{\.cabal$})
end

# Add files and commands to this file, like the example:
#   watch(%r{file/path}) { `command(s)` }
#
guard :shell do
  watch(%r{src/.+\.l?hs$}) {|m| `/usr/bin/notify-send "Compile is finished"` }
end
